class_name FileNames

const Level = "res://levels_data/level.json"
const Player = "res://game_components/player/player.tscn"
const FixedBlocks = "res://game_components/obstacles/fixed_block/fixed_block.tscn"
const ShiftingBlocks = "res://game_components/obstacles/shifting_block/shifting_block.tscn"
const ExitPoint = "res://game_components/obstacles/exit_point/exit_point.tscn"
const SignalGate = "res://game_components/obstacles/signal_gate/signal_gate.tscn"
const FixedDangerZone = "res://game_components/obstacles/danger_zone/fixed_danger_zone.tscn"
const ShiftingDangerZone = "res://game_components/obstacles/danger_zone/shifting_danger_zone.tscn"
const TimedDangerZone = "res://game_components/obstacles/danger_zone/timed_danger_zone.tscn"
const GameDialogs = "res://game_components/ui/game_dialogs.tscn"
const TouchControls = "res://game_components/ui/touch_controls.tscn"
const MainMenu = "res://screens/main_menu/main_menu.tscn"
const LevelSelect = "res://screens/level_select/level_select.tscn"
const SaveData = "user://save_data.json"
